[build]
  publish = "site"

[build.processing]
  skip_processing = true

[[redirects]]
  from = "/tax-analyzer.html"
  to = "/tax-analyzer.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/home.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]
